services:
  db:
    image: postgres:latest
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_DB: coffee_orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - springnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: coffee-order-service
    container_name: spring_boot_order_app
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - springnet
    environment:
#      for ec2
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coffee_orders
#      local
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/coffee_orders
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

networks:
  springnet:
    driver: bridge

volumes:
  postgres_data:  # Ensure data persists